spring.application.name=audience-insights-auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/audience_insights
spring.datasource.username=postgres
spring.datasource.password=0060

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
